In [1]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import metrics
import seaborn as sns



In [2]:
mat = np.array([[1,2,3], [2,5,6]])
print(mat)  

# Tuple = () You cannot do modification on this.
# List = [] You can do modification on this.
# Set = ([]) Set is mytable but its element are immutable.
# Mutable = something that can be changed or modified.
# Dictionary = '''{} Dict is unordered collectuon of values stred as <key values> pair. A key in dictionary must be immutable and Unique'''

[[1 2 3]
 [2 5 6]]


In [3]:
a = [1,2,3,4, 'abc', 'xyz']
type(a)

list

In [4]:
a.append('abc')
a
a.pop(5) #Defalut indexing of -1


'xyz'

In [5]:
del a[5]

In [6]:
a.insert(4, 'abc')
a
    

[1, 2, 3, 4, 'abc', 'abc']

In [7]:
a = [1, 2, 3, 4, 5]
# multiplier = 3

result = [x * 3 for x in a]

print(result)


[3, 6, 9, 12, 15]


In [8]:
x = ([1,2,5], 8.5, 9.6, 'abc', [True, False]) #Tuple
list(x) #converts into a list

[[1, 2, 5], 8.5, 9.6, 'abc', [True, False]]

In [9]:
x = list(x)

set(x)  #returns the unqiue numbers but error coming

TypeError: unhashable type: 'list'

In [ ]:
x = (8.5, 9.6, 'abc')

In [ ]:
set(x)

In [ ]:
x1 = {'id1' :8.5}
type(x1)

In [ ]:
X5 = [1,2,3,4,5,6,7,8,9,10]
X5[5] = True
X5

In [ ]:
X5 = tuple(X5)
type(X5)

In [ ]:
id(X5)

In [ ]:
X6 = X5

In [ ]:
id(X6), id(X5)

In [ ]:
captains = {
    "Enterprise": "Picard",
    "Voyager": "Janeway",
    "Defiant": "Sisko",
    "Discovery": "unknown",
}

In [ ]:
del captains["Discovery"]

In [ ]:
captains.pop("Discovery")

In [ ]:
captains

In [ ]:
a = [1, 2, 3, 4, 5]
a

In [ ]:
a[2:2] = []
a

In [ ]:
a = [1,2,3,4,5]
a.remove(3)

In [ ]:
a

In [ ]:
t = ('foo', 'bar', 'baz')

In [ ]:
t[1] = 'qux'

In [ ]:
{1, 2, 3, 4, 5} - {3, 4} ^ {5, 6, 7}

In [ ]:
employee = {
    "id": 1701,
    "name": "James T Kirk",
    "email": "jtkirk@starfleet.com",
    "position": "captain",
}

In [ ]:
print(employee["email"])

In [ ]:
captains = {}

In [ ]:
captains

In [ ]:
a = [1,2,3,4,5]
# a[2] = []
a

In [ ]:
captains = {
    "Enterprise": "Picard",
    "Voyager": "Janeway",
    "Defiant": "Sisko",
    "Discovery": "unknown",
}

# del captains["Discovery"]

In [ ]:
captains

In [ ]:
captains.dict()

In [ ]:
captains

# Control Flow Statements

### Conditional Statements. Loops. Functions

In [10]:
### Single level condition
### Multiple condition
### Multi level condition


In [17]:
a = 10
b = 5

if a>10:
    print("number is greator than 10")
else:
    print("number is not greator than 10")
    

number is not greator than 10


In [19]:
# (&) is used to save time as it will reduce execution timing
# (and) is operator for logical reference and works directly without using brackets on condition
# for OR operator we use |

# (x|y)&z will execute with parenthesis first and then with z


In [20]:
# Multi level

a=10
b=15
c=20

if a>10:
    print("Greator than 10")
elif a>5:
    print("greator than 5 but less than 10")
elif a>2:
    print('greator than 2 and less than five')
else:
    print('NULL')

greator than 5 but less than 10


In [25]:
i = 1
while i<11:
    sq=i*i
    print(sq)
    i=i+1
    


1
4
9
16
25
36
49
64
81
100


In [ ]:
number = int(input("Enter the number u want square \n"))
i = 1
def Sq(number):
    if number < 0:
        return ("Enter the valid number")
    else:
        for i in range(1,number+1):
            k = i*i
        print(f"The square of {number} is {Sq(number)}")

print(Sq(number))
    
    

Enter the number u want square 
7


In [25]:
import numpy as np

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
name = input("Enter the word u want to check  ")


Str=name
lower=0
upper=0
for i in Str:
      if(i.islower()):
            lower+=1
      else:
            upper+=1
print("The number of lowercase characters is:",lower)
print("The number of uppercase characters is:",upper)


    



Enter the word u want to check  KJNJKM
The number of lowercase characters is: 0
The number of uppercase characters is: 6


In [22]:
i=1
for i in range(0,51,2):
    print(i*i)

0
4
16
36
64
100
144
196
256
324
400
484
576
676
784
900
1024
1156
1296
1444
1600
1764
1936
2116
2304
2500


In [28]:
def square(num1, num2):
    for i in np.arange(num1, num2+1):
        print('Square of {} is {}'.format(i,i**2))
print(square(1,10))

Square of 1 is 1
Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
Square of 6 is 36
Square of 7 is 49
Square of 8 is 64
Square of 9 is 81
Square of 10 is 100
None
